/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subhan.gradle.cicd.example;

import org.junit.Assert;
import org.junit.Test;

import java.util.stream.Collectors;

import static org.junit.Assert.assertNotNull;

public class DataTest {

    static int THRESHOLD = 79; //to make this fail more, increase this number.

    @Test
    public void testDataIntegrity() {

        App a = new App();

        int sum = a.getData().parallelStream().mapToInt(Integer::intValue).reduce(0, Integer::sum);

        System.out.printf("is %d > %d?", sum, THRESHOLD);

        Assert.assertTrue(sum >= THRESHOLD);

    }
}
