/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subhan.gradle.cicd.example;

import java.util.ArrayList;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public ArrayList<Integer> getData() {
        Random r = new Random();

        ArrayList<Integer> data = new ArrayList<>();

        int i = 20;
        while (i > 0) {

            data.add(r.nextInt(0, 10));

            i--;
        }
        return data;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
